services:
  service_catalog:
    build:
      context: ./service_catalog
    ports:
      - "8080:8080"
    volumes:
      - ./service_catalog:/app
    networks:
      - gym-genius-network

  resource_catalog:
    build:
      context: ./resource_catalog
    ports:
      - "8081:8081"
    volumes:
      - ./resource_catalog:/app
    networks:
      - gym-genius-network

  device_connector:
    build:
      context: ./device_connector
    ports:
      - "8082:8082"
    volumes:
      - ./device_connector:/app
    networks:
      - gym-genius-network

  entry_sensor:
    build:
      context: ./sensors
    command: python entrance_button.py
    volumes:
      - ./sensors:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
    environment:
      - DEVICE_CONNECTOR_URL=http://device_connector:8082

  exit_sensor:
    build:
      context: ./sensors
    command: python simulate_button.py 
    volumes:
      - ./sensors:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
    environment:
      - DEVICE_CONNECTOR_URL=http://device_connector:8082

networks:
  gym-genius-network:
    driver: bridge
