version: '3'

services:
  # Device Connector Service
  device_connector:
    build:
      context: ./device_connector  # Path to the Dockerfile in the device_connector directory
    ports:
      - "8082:8082"
    volumes:
      - ./device_connector:/app  # Mount the local folder to the container
    networks:
      - gym-genius-network

  # Temperature Optimization Service
  temperature_optimization:
    build:
      context: ./temp_optimization  # Path to the Dockerfile in temp_optimization directory
    volumes:
      - ./temp_optimization:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
      - service_catalog
      - resource_catalog

  # Occupancy Monitoring Service
  occupancy:
    build:
      context: ./occupancy  # Path to the Dockerfile in occupancy directory
    volumes:
      - ./occupancy:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
      - service_catalog
      - resource_catalog

  # Machine Availability Service
  machine_availability:
    build:
      context: ./machine_availability  # Path to the Dockerfile in machine_availability directory
    volumes:
      - ./machine_availability:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
      - service_catalog
      - resource_catalog

  # Thingspeak Adaptor Service
  thingspeak_adaptor:
    build:
      context: ./thingspeak  # Path to the Dockerfile in thingspeak directory
    ports:
      - "8080:8080"
    volumes:
      - ./thingspeak:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
      - service_catalog
      - resource_catalog

  # Telegram Bot Service
  telegram_bot:
    build:
      context: ./telegramBot  # Path to the Dockerfile in telegramBot directory
    ports:
      - "8086:8086"
    volumes:
      - ./telegramBot:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
      - service_catalog
      - resource_catalog

  # Button Sensor (real and simulated)
  button_sensor:
    build:
      context: ./sensors  # Path to the Dockerfile in sensors directory
    command: python button.py  # Command to run the button.py script
    volumes:
      - ./sensors:/app  # Mount the local sensors folder to the container
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
    devices:
      - "/dev/mem:/dev/mem"  # Needed for GPIO access on Raspberry Pi

  # DHT11 Sensor (real and simulated)
  dht11_sensor:
    build:
      context: ./sensors  # Path to the Dockerfile in sensors directory
    command: python dht11.py  # Command to run the dht11.py script
    volumes:
      - ./sensors:/app  # Mount the local sensors folder to the container
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
    devices:
      - "/dev/mem:/dev/mem"  # Needed for GPIO access on Raspberry Pi

  # PIR Sensor (real and simulated)
  pir_sensor:
    build:
      context: ./sensors  # Path to the Dockerfile in sensors directory
    command: python PIR_sensor.py  # Command to run the PIR_sensor.py script
    volumes:
      - ./sensors:/app  # Mount the local sensors folder to the container
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
    devices:
      - "/dev/mem:/dev/mem"  # Needed for GPIO access on Raspberry Pi

  # Entry Sensor Simulation (part of occupancy)
  entry_sensor:
    build:
      context: ./sensors  # Path to the Dockerfile in sensors directory
    command: python button.py  # Command to run the button.py for entry simulation
    volumes:
      - ./sensors:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
    environment:
      - DEVICE_CONNECTOR_URL=http://device_connector:8082

  # Exit Sensor Simulation (part of occupancy)
  exit_sensor:
    build:
      context: ./sensors  # Path to the Dockerfile in sensors directory
    command: python simulate_button.py  # Command to run the simulate_button.py for exit simulation
    volumes:
      - ./sensors:/app
    networks:
      - gym-genius-network
    depends_on:
      - device_connector
    environment:
      - DEVICE_CONNECTOR_URL=http://device_connector:8082

networks:
  gym-genius-network:
    driver: bridge
